# Generated by Django 5.1.5 on 2025-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_task_due_date_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='task_uploads/'),
        ),
    ]
