# Generated by Django 5.1.5 on 2025-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users_details",
            name="role",
            field=models.CharField(default="user", max_length=50),
        ),
        migrations.AlterField(
            model_name="users_details",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
