# Generated by Django 5.1.5 on 2025-01-27 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0003_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to="apt_app.users_details",
            ),
        ),
    ]
