# Generated by Django 5.1.5 on 2025-01-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0004_alter_tasks_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
