# Generated by Django 5.1.5 on 2025-02-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0005_tasks_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_by",
                to="apt_app.users_details",
                to_field="user_name",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to="apt_app.users_details",
                to_field="user_name",
            ),
        ),
        migrations.AlterField(
            model_name="users_details",
            name="user_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
