# Generated by Django 5.1.5 on 2025-02-03 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0006_alter_tasks_assigned_by_alter_tasks_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_by",
                to="apt_app.users_details",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to="apt_app.users_details",
            ),
        ),
        migrations.AlterField(
            model_name="users_details",
            name="user_name",
            field=models.CharField(max_length=100),
        ),
    ]
