# Generated by Django 5.1.5 on 2025-02-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0007_alter_tasks_assigned_by_alter_tasks_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="answer",
            field=models.TextField(null=True),
        ),
    ]
